# Generated by Django 5.2 on 2025-04-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.TextField()),
                ('sinopse', models.TextField()),
                ('ano', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('capa', models.TextField(default='')),
            ],
        ),
    ]
